import fs from 'fs';
import path from 'path';

import Environment from '#/util/Environment.js';
import { listPlugins, pluginsRoot } from '#tools/plugins/PluginPacks.js';

/**
 * Generates the two things a content plugin cannot express for itself.
 *
 * **Flags.** RuneScript cannot read server config - only `map_members` and `map_live` are exposed
 * as ops - so a content plugin has no runtime switch of its own. Instead the enabled state is
 * compiled in as a constant, which content can branch on like any other value. Toggling therefore
 * needs a repack, which is the same cost as editing any other content.
 *
 * **Hooks.** RuneScript triggers are single-owner: there is exactly one `[login,_]` in the whole
 * game, so two plugins cannot both react to login, and neither can react at all without editing
 * core content. The generated dispatcher is what makes that possible - core calls one proc, and
 * that proc calls whichever plugins defined a matching one.
 *
 * Both files are derived. Never edit them; edit the plugin or the config and re-run the sync.
 */
export const HOOKS = ['login', 'logout'] as const;
export type Hook = (typeof HOOKS)[number];

const GENERATED = '_generated';

export type PluginState = {
    name: string;
    enabled: boolean;
    hooks: Hook[];
};

function configPath(): string {
    return path.resolve('data/config/plugins.json');
}

/** A plugin is on unless `data/config/plugins.json` lists it under `disabled`. */
function disabledSet(): Set<string> {
    if (!fs.existsSync(configPath())) {
        return new Set();
    }

    try {
        const parsed: unknown = JSON.parse(fs.readFileSync(configPath(), 'utf8'));
        const disabled = (parsed as { disabled?: unknown })?.disabled;
        return Array.isArray(disabled) ? new Set(disabled.map(String)) : new Set();
    } catch {
        return new Set();
    }
}

/** Which hooks a plugin implements, by looking for `[proc,<plugin>_<hook>]` in its scripts. */
function hooksOf(plugin: string): Hook[] {
    const dir = path.join(pluginsRoot(), plugin, 'scripts');

    if (!fs.existsSync(dir)) {
        return [];
    }

    let source = '';
    for (const file of fs.readdirSync(dir)) {
        if (file.endsWith('.rs2')) {
            source += fs.readFileSync(path.join(dir, file), 'utf8');
        }
    }

    return HOOKS.filter(hook => new RegExp(`^\\[proc,${plugin}_${hook}\\]`, 'm').test(source));
}

export function pluginStates(): PluginState[] {
    const disabled = disabledSet();

    return listPlugins().map(name => ({ name, enabled: !disabled.has(name), hooks: hooksOf(name) }));
}

export function generate(): { constants: string; hooks: string; states: PluginState[] } {
    const states = pluginStates();

    const constants =
        '// GENERATED by tools/plugins/SyncPluginPacks.ts - do not edit.\n' +
        '// A plugin is enabled unless listed under "disabled" in engine/data/config/plugins.json.\n\n' +
        states.map(s => `^plugin_${s.name}_enabled = ${s.enabled ? 1 : 0}`).join('\n') +
        '\n';

    let hooks =
        '// GENERATED by tools/plugins/SyncPluginPacks.ts - do not edit.\n' +
        '//\n' +
        '// RuneScript triggers are single-owner, so plugins cannot each own [login,_]. Core content\n' +
        '// calls one dispatcher per hook and this file fans it out to whichever plugins implement it,\n' +
        '// guarded by the enabled flag. A plugin opts in by defining [proc,<plugin>_<hook>].\n';

    for (const hook of HOOKS) {
        const implementers = states.filter(s => s.hooks.includes(hook));
        hooks += `\n[proc,plugin_${hook}]\n`;

        if (implementers.length === 0) {
            hooks += `// no plugin implements ${hook}\n`;
            continue;
        }

        for (const s of implementers) {
            // the constant has to land in a typed context first: the compiler cannot infer a
            // type when a bare ^constant is compared against a literal
            hooks += `def_int $${s.name}_on = ^plugin_${s.name}_enabled;\n`;
            hooks += `if ($${s.name}_on = 1) {\n    ~${s.name}_${hook};\n}\n`;
        }
    }

    return { constants, hooks, states };
}

export function write(): PluginState[] {
    const { constants, hooks, states } = generate();
    const root = path.resolve(`${Environment.build.srcDir}/scripts/plugins/${GENERATED}`);

    fs.mkdirSync(path.join(root, 'configs'), { recursive: true });
    fs.mkdirSync(path.join(root, 'scripts'), { recursive: true });
    writeIfChanged(path.join(root, 'configs', 'plugins.constant'), constants);
    writeIfChanged(path.join(root, 'scripts', 'hooks.rs2'), hooks);

    return states;
}

function writeIfChanged(file: string, content: string): void {
    if (fs.existsSync(file) && fs.readFileSync(file, 'utf8') === content) {
        return;
    }
    fs.writeFileSync(file, content);
}
